#' metis.mappings
#'
#' This function has all the mappings used to convert between different categories
#'
#' List of Mappings
#' @param name Default=NULL. Name of assumption object.
#' \itemize{
#' \item mapParamQuery}
#' @keywords assumptions
#' @return A list of assumptions
#' @export
#' @examples
#' library(metis)
#' a<-metis.mappings()
#' a # will give full list of mappings
#' @importFrom magrittr %>%

metis.mappings <- function(name=NULL) {

  #------------------------------------------------------------
  # Metis param, query, palette, maps Mapping
  #-----------------------------------------------------------

  # Used by metis.readgcam()
  # USed by metis.mapsProcess()

  mapParamQuery <- tibble::tribble(
    ~group, ~param, ~query,~mapPalette,
    "energy","energyPrimaryByFuelEJ","primary energy consumption by region (direct equivalent)","pal_hot",
    "energy","energyPrimaryRefLiqProdEJ", "refined liquids production by subsector","pal_hot",
    "energy","energyFinalConsumBySecEJ", "total final energy by aggregate sector","pal_hot",
    "energy","energyFinalByFuelBySectorEJ", "Final energy by detailed end-use sector and fuel","pal_hot",
    "energy","energyFinalSubsecByFuelTranspEJ", "transport final energy by fuel","pal_hot",
    "energy","energyFinalSubsecByFuelBuildEJ", "building final energy by fuel","pal_hot",
    "energy","energyFinalSubsecByFuelIndusEJ", "industry final energy by fuel","pal_hot",
    "energy","energyFinalSubsecBySectorBuildEJ", "building final energy by subsector","pal_hot",
    "energy","energyFinalConsumByIntlShpAvEJ", "transport final energy by mode and fuel","pal_hot",
    "energy","energyPrimaryByFuelMTOE", "primary energy consumption by region (direct equivalent)","pal_hot",
    "energy","energyPrimaryRefLiqProdMTOE", "refined liquids production by subsector","pal_hot",
    "energy","energyFinalConsumBySecMTOE", "total final energy by aggregate sector","pal_hot",
    "energy","energyFinalbyFuelMTOE", "Final energy by detailed end-use sector and fuel","pal_hot",
    "energy","energyFinalSubsecByFuelTranspMTOE", "transport final energy by fuel","pal_hot",
    "energy","energyFinalSubsecByFuelBuildMTOE", "building final energy by fuel","pal_hot",
    "energy","energyFinalSubsecByFuelIndusMTOE", "industry final energy by fuel","pal_hot",
    "energy","energyFinalSubsecBySectorBuildMTOE", "building final energy by subsector","pal_hot",
    "energy","energyFinalConsumByIntlShpAvMTOE", "transport final energy by mode and fuel","pal_hot",
    "energy","energyPrimaryByFuelTWh", "primary energy consumption by region (direct equivalent)","pal_hot",
    "energy","energyPrimaryRefLiqProdTWh", "refined liquids production by subsector","pal_hot",
    "energy","energyFinalConsumBySecTWh", "total final energy by aggregate sector","pal_hot",
    "energy","energyFinalbyFuelTWh", "Final energy by detailed end-use sector and fuel","pal_hot",
    "energy","energyFinalSubsecByFuelTranspTWh", "transport final energy by fuel","pal_hot",
    "energy","energyFinalSubsecByFuelBuildTWh", "building final energy by fuel","pal_hot",
    "energy","energyFinalSubsecByFuelIndusTWh", "industry final energy by fuel","pal_hot",
    "energy","energyFinalSubsecBySectorBuildTWh", "building final energy by subsector","pal_hot",
    "energy","energyFinalConsumByIntlShpAvTWh", "transport final energy by mode and fuel","pal_hot",
    # Electricity
    "electricity","elecByTechTWh", c("elec gen by gen tech cogen USA","elec gen by gen tech USA","elec gen by gen tech and cooling tech"),"pal_hot",
    "electricity","elecCapByFuel", c("elec gen by gen tech cogen USA","elec gen by gen tech USA","elec gen by gen tech and cooling tech"),"pal_hot",
    "electricity","elecFinalBySecTWh", "Final energy by detailed end-use sector and fuel","pal_hot",
    "electricity","elecFinalByFuelTWh", "Final energy by detailed end-use sector and fuel","pal_hot",
    "electricity","elecNewCapCost", c("elec gen by gen tech and cooling tech and vintage","Electricity generation by aggregate technology"),"pal_hot",
    "electricity","elecNewCapGW", c("elec gen by gen tech and cooling tech and vintage","Electricity generation by aggregate technology"),"pal_hot",
    "electricity","elecAnnualRetPrematureCost", c("elec gen by gen tech and cooling tech and vintage","Electricity generation by aggregate technology"),"pal_hot",
    "electricity","elecAnnualRetPrematureGW", c("elec gen by gen tech and cooling tech and vintage","Electricity generation by aggregate technology"),"pal_hot",
    "electricity","elecCumCapCost", c("elec gen by gen tech and cooling tech and vintage","Electricity generation by aggregate technology"),"pal_hot",
    "electricity","elecCumCapGW", c("elec gen by gen tech and cooling tech and vintage","Electricity generation by aggregate technology"),"pal_hot",
    "electricity","elecCumRetPrematureCost", c("elec gen by gen tech and cooling tech and vintage","Electricity generation by aggregate technology"),"pal_hot",
    "electricity","elecCumRetPrematureGW", c("elec gen by gen tech and cooling tech and vintage","Electricity generation by aggregate technology"),"pal_hot",
    # Transport
    "transport","transportPassengerVMTByMode", "transport service output by mode","pal_hot",
    "transport","transportFreightVMTByMode", "transport service output by mode","pal_hot",
    "transport","transportPassengerVMTByFuel","transport service output by tech (new)","pal_hot",
    "transport","transportFreightVMTByFuel", "transport service output by tech (new)","pal_hot",
    # Water
    "water","watConsumBySec", "water consumption by state, sector, basin (includes desal)","pal_wet",
    "water","watWithdrawBySec", "water withdrawals by state, sector, basin (includes desal)","pal_wet",
    "water","watWithdrawByCrop", "water withdrawals by crop","pal_wet",
    "water","watBioPhysCons", "biophysical water demand by crop type and land region","pal_wet",
    "water","watIrrWithdrawBasin", "water withdrawals by water mapping source","pal_wet",
    "water","watIrrConsBasin", "water consumption by water mapping source","pal_wet",
    "water","watSupRunoffBasin", "Basin level available runoff","pal_wet",
    "water","waterWithdrawROGW", "Water withdrawals by water source (runoff vs. groundwater)","pal_wet",
    # Socio-economics
    "socioecon","gdpPerCapita", "GDP per capita MER by region","pal_hot",
    "socioecon","gdp", "GDP MER by region","pal_hot",
    "socioecon","gdpGrowthRate", "GDP Growth Rate (Percent)","pal_hot",
    "socioecon","pop", "Population by region","pal_hot",
    # Agriculture
    "ag","agProdbyIrrRfd", "ag production by tech","pal_green",
    "ag","agProdBiomass", "ag production by tech","pal_green",
    "ag","agProdForest", "ag production by tech","pal_green",
    "ag","agProdByCrop", "ag production by tech","pal_green",
    #Livestock
    "livestock","livestock_MeatDairybyTechMixed", "meat and dairy production by tech","pal_green",
    "livestock","livestock_MeatDairybyTechPastoral", "meat and dairy production by tech","pal_green",
    "livestock","livestock_MeatDairybyTechImports", "meat and dairy production by tech","pal_green",
    "livestock","livestock_MeatDairybySubsector", "meat and dairy production by tech","pal_green",
    # Land use
    "land","landIrrRfd", "land allocation by crop and water source","pal_green",
    "land","landIrrCrop", "land allocation by crop and water source","pal_green",
    "land","landRfdCrop", "land allocation by crop and water source","pal_green",
    "land","landAlloc", "aggregated land allocation","pal_green",
    "land","landAllocByCrop", "land allocation by crop","pal_green",
    "land","landAllocDetail","detailed land allocation","pal_green",
    # General
    "general","inputs", "inputs by tech","pal_hot",
    "general","outputs", "outputs by tech","pal_hot",
    # Emissions
    "emissions","emissNonCO2BySectorGWPAR5", "nonCO2 emissions by sector","pal_hot",
    "emissions","emissNonCO2BySectorGTPAR5", "nonCO2 emissions by sector","pal_hot",
    "emissions","emissNonCO2BySectorOrigUnits", "nonCO2 emissions by sector","pal_hot",
    "emissions","emissLUC", "Land Use Change Emission (future)","pal_hot",
    "emissions","emissCO2BySectorNoBio", "CO2 emissions by sector (no bio)","pal_hot",
    "emissions","emissNonCO2ByResProdGWPAR5", "nonCO2 emissions by resource production","pal_hot",
    "emissions","emissMethaneBySourceGWPAR5", "nonCO2 emissions by sector","pal_hot",
    "emissions","emissByGasGWPAR5FFI", c("nonCO2 emissions by resource production","nonCO2 emissions by sector"),"pal_hot",
    "emissions","emissByGasGWPAR5LUC", c("nonCO2 emissions by resource production","nonCO2 emissions by sector"),"pal_hot",
    "emissions","emissBySectorGWPAR5FFI", c("nonCO2 emissions by resource production","nonCO2 emissions by sector"),"pal_hot",
    "emissions","emissBySectorGWPAR5LUC", c("nonCO2 emissions by resource production","nonCO2 emissions by sector"),"pal_hot",
    "emissions","emissNonCO2ByResProdGTPAR5", "nonCO2 emissions by resource production","pal_hot",
    "emissions","emissMethaneBySourceGTPAR5", "nonCO2 emissions by sector","pal_hot",
    "emissions","emissByGasGTPAR5FFI", c("nonCO2 emissions by resource production","nonCO2 emissions by sector"),"pal_hot",
    "emissions","emissByGasGTPAR5LUC", c("nonCO2 emissions by resource production","nonCO2 emissions by sector"),"pal_hot",
    "emissions","emissBySectorGTPAR5FFI",  c("nonCO2 emissions by resource production","nonCO2 emissions by sector"),"pal_hot",
    "emissions","emissBySectorGTPAR5LUC", c("nonCO2 emissions by resource production","nonCO2 emissions by sector"),"pal_hot",
  ); mapParamQuery

  #--------------------------------------------------------------------------------------------------
  # Country to GCAM 32 Region Mapping
  #--------------------------------------------------------------------------------------------------

  countryToGCAMReg32 <- tibble::tribble(
    ~region_code	,	~ctry_code	,	~region	,	~ctry_name	,
    29	,	238	, "Southeast Asia", "Fiji",
    23	,	103	, "Russia", "Russia",
    13	,	17	, "EU-15", "Wallis & Futuna",
    6	,	223	, "Australia_NZ", "New Zealand",
    1	,	150	, "USA", "United States",
    29	,	40	, "Southeast Asia", "Midway Is.",
    29	,	16	, "Southeast Asia", "Tonga",
    29	,	38	, "Southeast Asia", "Kiribati",
    29	,	14	, "Southeast Asia", "Samoa",
    29	,	15	, "Southeast Asia", "Tokelau",
    29	,	9	, "Southeast Asia", "American Samoa",
    29	,	13	, "Southeast Asia", "Niue",
    29	,	37	, "Southeast Asia", "Johnston Atoll",
    29	,	10	, "Southeast Asia", "Cook Is.",
    29	,	11	, "Southeast Asia", "French Polynesia",
    8	,	34	, "Canada", "Canada",
    29	,	3	, "Southeast Asia", "Pitcairn Is.",
    20	,	39	, "Mexico", "Mexico",
    26	,	21	, "South America_Southern", "Chile",
    9	,	35	, "Central America and Caribbean", "Guatemala",
    26	,	22	, "South America_Southern", "Ecuador",
    9	,	62	, "Central America and Caribbean", "El Salvador",
    9	,	63	, "Central America and Caribbean", "Honduras",
    9	,	57	, "Central America and Caribbean", "Belize",
    9	,	64	, "Central America and Caribbean", "Nicaragua",
    9	,	60	, "Central America and Caribbean", "Costa Rica",
    9	,	61	, "Central America and Caribbean", "Cuba",
    9	,	65	, "Central America and Caribbean", "Panama",
    32	,	59	, "Colombia", "Colombia",
    26	,	24	, "South America_Southern", "Peru",
    9	,	58	, "Central America and Caribbean", "Cayman Is.",
    9	,	55	, "Central America and Caribbean", "The Bahamas",
    9	,	53	, "Central America and Caribbean", "Jamaica",
    9	,	52	, "Central America and Caribbean", "Haiti",
    7	,	20	, "Brazil", "Brazil",
    31	,	18	, "Argentina", "Argentina",
    25	,	8	, "South America_Northern", "Venezuela",
    13	,	67	, "EU-15", "Greenland",
    13	,	56	, "EU-15", "Turks & Caicos Is.",
    9	,	51	, "Central America and Caribbean", "Dominican Republic",
    26	,	19	, "South America_Southern", "Bolivia",
    9	,	54	, "Central America and Caribbean", "Netherlands Antilles",
    1	,	30	, "USA", "Puerto Rico",
    1	,	32	, "USA", "Virgin Is.",
    9	,	50	, "Central America and Caribbean", "Bermuda",
    9	,	26	, "Central America and Caribbean", "Anguilla",
    9	,	31	, "Central America and Caribbean", "St. Kitts & Nevis",
    26	,	23	, "South America_Southern", "Paraguay",
    9	,	29	, "Central America and Caribbean", "Montserrat",
    9	,	7	, "Central America and Caribbean", "Trinidad & Tobago",
    9	,	43	, "Central America and Caribbean", "Grenada",
    9	,	44	, "Central America and Caribbean", "Guadeloupe",
    9	,	27	, "Central America and Caribbean", "Antigua & Barbuda",
    9	,	48	, "Central America and Caribbean", "St. Vincent & the Grenadines",
    9	,	45	, "Central America and Caribbean", "Martinique",
    9	,	42	, "Central America and Caribbean", "Dominica",
    13	,	0	, "EU-15", "Falkland Is.",
    25	,	2	, "South America_Northern", "Guyana",
    9	,	41	, "Central America and Caribbean", "Barbados",
    26	,	25	, "South America_Southern", "Uruguay",
    25	,	6	, "South America_Northern", "Suriname",
    13	,	47	, "EU-15", "St. Pierre & Miquelon",
    25	,	1	, "South America_Northern", "French Guiana",
    26	,	4	, "South America_Southern", "South Georgia & the South Sandwich Is.",
    13	,	81	, "EU-15", "Portugal",
    5	,	75	, "Africa_Western", "Cape Verde",
    16	,	69	, "European Free Trade Association", "Iceland",
    13	,	82	, "EU-15", "Spain",
    5	,	89	, "Africa_Western", "Senegal",
    5	,	88	, "Africa_Western", "Mauritania",
    3	,	83	, "Africa_Northern", "Western Sahara",
    5	,	91	, "Africa_Western", "The Gambia",
    5	,	86	, "Africa_Western", "Guinea-Bissau",
    5	,	85	, "Africa_Western", "Guinea",
    13	,	5	, "EU-15", "St. Helena",
    5	,	90	, "Africa_Western", "Sierra Leone",
    3	,	80	, "Africa_Northern", "Morocco",
    5	,	87	, "Africa_Western", "Mali",
    5	,	79	, "Africa_Western", "Liberia",
    13	,	70	, "EU-15", "Ireland",
    16	,	72	, "European Free Trade Association", "Jan Mayen",
    5	,	76	, "Africa_Western", "Cote d'Ivoire",
    3	,	106	, "Africa_Northern", "Algeria",
    13	,	74	, "EU-15", "United Kingdom",
    13	,	66	, "EU-15", "Faroe Is.",
    5	,	84	, "Africa_Western", "Burkina Faso",
    13	,	145	, "EU-15", "France",
    13	,	71	, "EU-15", "Isle of Man",
    5	,	77	, "Africa_Western", "Ghana",
    13	,	68	, "EU-15", "Guernsey",
    13	,	73	, "EU-15", "Jersey",
    5	,	119	, "Africa_Western", "Togo",
    5	,	116	, "Africa_Western", "Niger",
    5	,	111	, "Africa_Western", "Benin",
    5	,	117	, "Africa_Western", "Nigeria",
    13	,	144	, "EU-15", "Belgium",
    13	,	248	, "EU-15", "Netherlands",
    16	,	102	, "European Free Trade Association", "Norway",
    5	,	118	, "Africa_Western", "Sao Tome & Principe",
    13	,	148	, "EU-15", "Luxembourg",
    13	,	146	, "EU-15", "Germany",
    16	,	149	, "European Free Trade Association", "Switzerland",
    13	,	123	, "EU-15", "Italy",
    3	,	110	, "Africa_Northern", "Tunisia",
    5	,	115	, "Africa_Western", "Equatorial Guinea",
    13	,	138	, "EU-15", "Denmark",
    5	,	220	, "Africa_Western", "Gabon",
    5	,	112	, "Africa_Western", "Cameroon",
    3	,	108	, "Africa_Northern", "Libya",
    13	,	136	, "EU-15", "Austria",
    13	,	104	, "EU-15", "Sweden",
    16	,	143	, "European Free Trade Association", "Svalbard",
    5	,	218	, "Africa_Western", "Congo Rep.",
    4	,	222	, "Africa_Southern", "Namibia",
    4	,	217	, "Africa_Southern", "Angola",
    5	,	219	, "Africa_Western", "Congo DRC",
    12	,	137	, "EU-12", "Czech Republic",
    5	,	114	, "Africa_Western", "Chad",
    15	,	122	, "Europe_Non_EU", "Croatia",
    12	,	142	, "EU-12", "Slovenia",
    12	,	125	, "EU-12", "Malta",
    5	,	113	, "Africa_Western", "Central African Republic",
    12	,	140	, "EU-12", "Poland",
    15	,	121	, "Europe_Non_EU", "Bosnia & Herzegovina",
    24	,	224	, "South Africa", "South Africa",
    12	,	139	, "EU-12", "Hungary",
    12	,	141	, "EU-12", "Slovakia",
    15	,	247	, "Europe_Non_EU", "Montenegro",
    15	,	120	, "Europe_Non_EU", "Albania",
    15	,	246	, "Europe_Non_EU", "Serbia",
    13	,	132	, "EU-15", "Greece",
    13	,	153	, "EU-15", "Finland",
    4	,	202	, "Africa_Southern", "Botswana",
    15	,	124	, "Europe_Non_EU", "Macedonia",
    12	,	157	, "EU-12", "Romania",
    12	,	155	, "EU-12", "Lithuania",
    12	,	154	, "EU-12", "Latvia",
    12	,	152	, "EU-12", "Estonia",
    4	,	207	, "Africa_Southern", "Zambia",
    2	,	95	, "Africa_Eastern", "Sudan",
    12	,	128	, "EU-12", "Bulgaria",
    14	,	158	, "Europe_Eastern", "Ukraine",
    14	,	151	, "Europe_Eastern", "Belarus",
    3	,	130	, "Africa_Northern", "Egypt",
    4	,	208	, "Africa_Southern", "Zimbabwe",
    15	,	135	, "Europe_Non_EU", "Turkey",
    4	,	221	, "Africa_Southern", "Lesotho",
    14	,	156	, "Europe_Eastern", "Moldova",
    2	,	203	, "Africa_Eastern", "Burundi",
    2	,	205	, "Africa_Eastern", "Rwanda",
    4	,	206	, "Africa_Southern", "Tanzania",
    2	,	96	, "Africa_Eastern", "Uganda",
    4	,	216	, "Africa_Southern", "Mozambique",
    4	,	225	, "Africa_Southern", "Swaziland",
    12	,	129	, "EU-12", "Cyprus",
    4	,	215	, "Africa_Southern", "Malawi",
    2	,	94	, "Africa_Eastern", "Ethiopia",
    2	,	204	, "Africa_Eastern", "Kenya",
    21	,	97	, "Middle East", "Gaza Strip",
    21	,	99	, "Middle East", "Israel",
    21	,	173	, "Middle East", "Saudi Arabia",
    21	,	100	, "Middle East", "Jordan",
    21	,	105	, "Middle East", "West Bank",
    21	,	133	, "Middle East", "Lebanon",
    21	,	134	, "Middle East", "Syria",
    2	,	93	, "Africa_Eastern", "Eritrea",
    21	,	98	, "Middle East", "Iraq",
    2	,	212	, "Africa_Eastern", "French Southern & Antarctic Lands",
    10	,	131	, "Central Asia", "Georgia",
    2	,	162	, "Africa_Eastern", "Somalia",
    2	,	92	, "Africa_Eastern", "Djibouti",
    21	,	166	, "Middle East", "Yemen",
    2	,	214	, "Africa_Eastern", "Juan De Nova I.",
    2	,	228	, "Africa_Eastern", "Madagascar",
    2	,	211	, "Africa_Eastern", "Comoros",
    10	,	167	, "Central Asia", "Armenia",
    21	,	170	, "Middle East", "Iran",
    29	,	230	, "Southeast Asia", "Mayotte",
    10	,	168	, "Central Asia", "Azerbaijan",
    29	,	232	, "Southeast Asia", "Seychelles",
    21	,	171	, "Middle East", "Kuwait",
    2	,	227	, "Africa_Eastern", "Glorioso Is.",
    10	,	101	, "Central Asia", "Kazakhstan",
    21	,	172	, "Middle East", "Qatar",
    21	,	169	, "Middle East", "Bahrain",
    21	,	174	, "Middle East", "United Arab Emirates",
    21	,	161	, "Middle East", "Oman",
    10	,	164	, "Central Asia", "Turkmenistan",
    2	,	231	, "Africa_Eastern", "Reunion",
    10	,	165	, "Central Asia", "Uzbekistan",
    2	,	229	, "Africa_Eastern", "Mauritius",
    27	,	175	, "South Asia", "Afghanistan",
    22	,	178	, "Pakistan", "Pakistan",
    10	,	179	, "Central Asia", "Tajikistan",
    17	,	159	, "India", "India",
    10	,	176	, "Central Asia", "Kyrgyzstan",
    27	,	226	, "South Asia", "British Indian Ocean Territory",
    6	,	213	, "Australia_NZ", "Heard I. & McDonald Is.",
    27	,	160	, "South Asia", "Maldives",
    11	,	183	, "China", "China",
    27	,	163	, "South Asia", "Sri Lanka",
    27	,	177	, "South Asia", "Nepal",
    27	,	180	, "South Asia", "Bangladesh",
    10	,	184	, "Central Asia", "Mongolia",
    27	,	181	, "South Asia", "Bhutan",
    29	,	190	, "Southeast Asia", "Myanmar",
    18	,	236	, "Indonesia", "Indonesia",
    29	,	235	, "Southeast Asia", "Cocos Is.",
    29	,	194	, "Southeast Asia", "Thailand",
    29	,	189	, "Southeast Asia", "Malaysia",
    29	,	188	, "Southeast Asia", "Laos",
    29	,	187	, "Southeast Asia", "Cambodia",
    29	,	195	, "Southeast Asia", "Vietnam",
    29	,	192	, "Southeast Asia", "Singapore",
    29	,	234	, "Southeast Asia", "Christmas I.",
    6	,	233	, "Australia_NZ", "Australia",
    29	,	182	, "Southeast Asia", "Brunei",
    29	,	186	, "Southeast Asia", "Philippines",
    30	,	183	, "Taiwan", "China",
    19	,	197	, "Japan", "Japan",
    29	,	237	, "Southeast Asia", "Timor-Leste",
    29	,	191	, "Southeast Asia", "North Korea",
    28	,	193	, "South Korea", "South Korea",
    29	,	185	, "Southeast Asia", "Palau",
    29	,	199	, "Southeast Asia", "Micronesia",
    29	,	242	, "Southeast Asia", "Papua New Guinea",
    29	,	196	, "Southeast Asia", "Guam",
    29	,	200	, "Southeast Asia", "Northern Mariana Is.",
    29	,	243	, "Southeast Asia", "Solomon Is.",
    29	,	198	, "Southeast Asia", "Marshall Is.",
    29	,	240	, "Southeast Asia", "New Caledonia",
    29	,	245	, "Southeast Asia", "Vanuatu",
    29	,	239	, "Southeast Asia", "Nauru",
    29	,	201	, "Southeast Asia", "Wake I.",
    29	,	241	, "Southeast Asia", "Norfolk I.",
    29	,	244	, "Southeast Asia", "Tuvalu",
    33	,	248	, "Uruguay", "Uruguay",
    33	,	150	, "AK", "United States",
    34	,	150	, "AL", "United States",
    35	,	150	, "AR", "United States",
    36	,	150	, "AZ", "United States",
    37	,	150	, "CA", "United States",
    38	,	150	, "CO", "United States",
    39	,	150	, "CT", "United States",
    40	,	150	, "DC", "United States",
    41	,	150	, "DE", "United States",
    42	,	150	, "FL", "United States",
    43	,	150	, "GA", "United States",
    44	,	150	, "HI", "United States",
    45	,	150	, "IA", "United States",
    46	,	150	, "ID", "United States",
    47	,	150	, "IL", "United States",
    48	,	150	, "IN", "United States",
    49	,	150	, "KS", "United States",
    50	,	150	, "KY", "United States",
    51	,	150	, "LA", "United States",
    52	,	150	, "MA", "United States",
    53	,	150	, "MD", "United States",
    54	,	150	, "ME", "United States",
    55	,	150	, "MI", "United States",
    56	,	150	, "MN", "United States",
    57	,	150	, "MO", "United States",
    58	,	150	, "MS", "United States",
    59	,	150	, "MT", "United States",
    60	,	150	, "NC", "United States",
    61	,	150	, "ND", "United States",
    62	,	150	, "NE", "United States",
    63	,	150	, "NH", "United States",
    64	,	150	, "NJ", "United States",
    65	,	150	, "NM", "United States",
    66	,	150	, "NV", "United States",
    67	,	150	, "NY", "United States",
    68	,	150	, "OH", "United States",
    69	,	150	, "OK", "United States",
    70	,	150	, "OR", "United States",
    71	,	150	, "PA", "United States",
    72	,	150	, "RI", "United States",
    73	,	150	, "SC", "United States",
    74	,	150	, "SD", "United States",
    75	,	150	, "TN", "United States",
    76	,	150	, "TX", "United States",
    77	,	150	, "UT", "United States",
    78	,	150	, "VA", "United States",
    79	,	150	, "VT", "United States",
    80	,	150	, "WA", "United States",
    81	,	150	, "WI", "United States",
    82	,	150	, "WV", "United States",
    83	,	150	, "WY", "United States"
  )

  #--------------------------------------------------------------------------------------------------
  # subRegion mapping to metis shapefile regions
  #--------------------------------------------------------------------------------------------------

  subRegionMap <- tibble::tribble(
    ~subRegion	,	~subRegionMetis,
    "ArkWhtRedR","Arkansas_White_Red",
    "California","California_River",
    "Caribbean","Caribbean",
    "FraserR","Fraser",
    "GreatBasin","Great",
    "GreatLakes","Great_Lakes",
    "MexCstNW","Mexico_Northwest_Coast",
    "MissouriR","Missouri_River",
    "MissppRN","Upper_Mississippi",
    "MissppRS","Lower_Mississippi_River",
    "NelsonR","Saskatchewan_Nelson",
    "OhioR","Ohio_River",
    "PacArctic","Pacific_and_Arctic_Coast",
    "RioGrande","Rio_Grande_River",
    "TennR","Tennessee_River",
    "TexasCst","Texas_Gulf_Coast",
    "UsaColoRN","Upper_Colorado_River",
    "UsaColoRS","Lower_Colorado_River",
    "UsaCstE","Mid_Atlantic",
    "UsaCstNE","New_England",
    "UsaCstSE","South_Atlantic_Gulf",
    "UsaPacNW","Pacific_Northwest")

  #--------------------------------------------------------------------------------------------------
  # Return Data
  #--------------------------------------------------------------------------------------------------

  listx <- list(
    mapParamQuery=mapParamQuery,
    countryToGCAMReg32=countryToGCAMReg32,
    subRegionMap=subRegionMap)

  if(!is.null(name)){returnx <- listx[[name]]} else {returnx <- listx }

  return(returnx)
}
