
#----------------------------
# Install necessary packages
#----------------------------
if("devtools" %in% rownames(installed.packages()) == F){install.packages("devtools")}
library(devtools)
#if("metis" %in% rownames(installed.packages()) == F){install_github(repo="zarrarkhan/metis")}    #andym : should this be changed to JGCRI/metis ?_?
library(metis)
if("rgcam" %in% rownames(installed.packages()) == F){install_github(repo="JGCRI/rgcam")}
library(rgcam)
if("tibble" %in% rownames(installed.packages()) == F){install.packages("tibble")}
library(tibble)
if("dplyr" %in% rownames(installed.packages()) == F){install.packages("dlpyr")}
library(dplyr)
if("rgdal" %in% rownames(installed.packages()) == F){install.packages("rgdal")}
library(rgdal)
if("tmap" %in% rownames(installed.packages()) == F){install.packages("tmap")}
library(tmap)
if("rgeos" %in% rownames(installed.packages()) == F){install.packages("rgeos")}
library(rgeos)
if("ggplot2" %in% rownames(installed.packages()) == F){install.packages("rgeos")}
library(ggplot2)



#------------------------
# Run Bia to create distributed electricity generation
#------------------------

biaOutputsFolder=paste(getwd(),"/dataFiles/grids/bia/biaOutputs",sep="")
biaInputsFolder=paste(getwd(),"/dataFiles/grids/bia/biaInputs",sep="")

biaScenarioAssign="Eg1"
biaInputsFiles=c("global_power_plant_database_MW")
#biaUnits="Capacity (MW)"   #andym   ?Should we have biaUnits?
popFolder<-paste(getwd(),"/dataFiles/grids/griddedIDsPop/",sep="")
popFiles<-"grid_pop_map"
popUnits<-"person"
#gridMetisData=paste(dirOutputs, "/Grids/gridMetisBIA.RData", sep = "")
#sqliteUSE = T andym
sqliteUSE = F #andym
sqliteDBNamePath =paste(getwd(),"/outputs/Grids/gridBIA.sqlite", sep = "")




gcamdatabasePath <-paste(getwd(),"/dataFiles/gcam",sep="")

gcamdatabaseName <-"example_database_basexdb"
gcamdataProjFile <-"Example_dataProj.proj"

# Use function localDBConn from package rgcam to get a list of scenarios if needed.
# localDBConn(gcamdatabasePath,gcamdatabaseName)
#dataProjLoaded <- loadProject(paste(gcamdatabasePath, "/", dataProj, sep = ""))
#  listScenarios(dataProjLoaded)  # List of Scenarios in GCAM database
# queries <- listQueries(dataProjLoaded)  # List of Queries in queryxml

queriesSelect = "All"      #andym
regionsSelect = "All"      #andym
#regionsSelect <- c("Colombia")
#regionsSelect <- NULL

reReadData=T  #andym


biaDistElecGen<-metis.bia(
            biaInputsFolder=biaInputsFolder,
            biaInputsFiles=biaInputsFiles,
            biaScenarioAssign=biaScenarioAssign,
            biaOutputsFolder=biaOutputsFolder,
            gridMetisData=gridMetisData,
            sqliteUSE = sqliteUSE,
            sqliteDBNamePath = sqliteDBNamePath,
            regionsSelect=regionsSelect, # Default Value is NULL
            reReadData=reReadData, # Default Value is T
            dataProj=gcamdataProjFile, # Default Value is "dataProj.proj"
            scenOrigNames=c("GCAMOrig","GCAMModified"),
            scenNewNames=c("GCAMOrig","GCAMModified"),
            gcamdatabasePath=gcamdatabasePath,
            gcamdatabaseName=gcamdatabaseName,
            queryxml="metisQueries.xml",  # Default Value is "metisQueries.xml"
            paramsSelect=c("elecByTech") # Default value is #andym electricity generated by subsector

)


# biaFolder=biaFolder
# biaFiles=biaFiles
# biaScenarioAssign=biaScenarioAssign
# biaOutputsFolder=biaOutputsFolder
# reReadData=reReadData
# gridMetisData=gridMetisData
# sqliteUSE = sqliteUSE
# sqliteDBNamePath = sqliteDBNamePath
# regionsSelect = NULL
# queriesSelect="All"

##andym old stuff:
# Grid to Shape
# gridMetisData<-paste(getwd(),"/outputs/Grids/gridMetis.RData",sep="")
# load(gridMetisData) # grid is called gridMetis
# grid<-gridMetis



